#services:
#  mysqldb:
#    container_name: mysqldb_container
#    image: mysql:8.0
#    ports:
#      # ë¡œì»¬ PCì˜ 13333 í¬íŠ¸ -> ì»¨í…Œì´ë„ˆì˜ 3306 í¬íŠ¸ë¡œ ì—°ê²°
#      - "13306:3306"
#    env_file:
#      - .env
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#      - --default-authentication-plugin=mysql_native_password
#    volumes:
#      - mysql_data:/var/lib/mysql
#    environment:
#      # .env íŒŒì¼ì—ì„œ ì§ì ‘ ë¡œë“œí•˜ê±°ë‚˜ ì—¬ê¸°ì— ëª…ì‹œ (í˜„ì¬ëŠ” ëª…ì‹œëœ ê°’ ì‚¬ìš©)
#      - TZ=Asia/Seoul
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    networks:
#      - portfolio
#
#  redis:
#    container_name: redis_container
#    image: redis:alpine
#    # ì¤‘ìš”: ë¹„ë°€ë²ˆí˜¸ ì„¤ì •(1234) ë° ë°ì´í„° ì§€ì†ì„± ì¼œê¸°(appendonly yes)
#    command: redis-server --requirepass "1234" --appendonly yes
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data



#  back_end:
#    image: jhh0101/portfolio:v
#    container_name: back_end_container
#    ports:
#      # ë¡œì»¬ PCì˜ 18888 í¬íŠ¸ -> ì»¨í…Œì´ë„ˆì˜ 8082 í¬íŠ¸ë¡œ ì—°ê²°
#      - "8888:8888"
#    environment:
#      - TZ=Asia/Seoul
#      - SPRING_PROFILES_ACTIVE=prod
#
#      # ğŸ¯ .env ê°’ ì£¼ì… (application.ymlì˜ Placeholderì™€ ì¼ì¹˜)
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
#
#      # ğŸ“§ ì´ë©”ì¼ ì„¤ì • ì¶”ê°€
#      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
#      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
#
#      # ğŸ” OAuth2 ì„¤ì •
#      - APP_BASE_URL=${APP_BASE_URL}
#      - FRONTEND_URL=${FRONTEND_URL}
#      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
#      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
#      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
#      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
#
#      # DB ì ‘ì† URL (HostëŠ” Docker ë„¤íŠ¸ì›Œí¬ ìƒì˜ 'mysql' ì„œë¹„ìŠ¤ ì´ë¦„)
#      - MYSQL_URL=jdbc:mysqldb://mysqldb:3306/portfolio?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#      - SPRING_DATASOURCE_URL=jdbc:mysqldb://mysqldb:3306/portfolio?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=none # application.ymlì˜ddl-auto ì„¤ì •ì„ ë”°ë¥´ê¸° ìœ„í•´ noneìœ¼ë¡œ ë³€ê²½
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect # ëª…ì‹œ
#    depends_on:
#      - mysql
#    networks:
#      - portfolio

#  front_end:
#    image: jhh0101/portfolio:v
#    build:
#      context: .
#
#    container_name: front_end_container
#    ports:
#      - "8880:80"
#    depends_on:
#      - backend
#    networks:
#      - portfolio

volumes:
  mysql_data:
  redis_data:

networks:
  portfolio:
    driver: bridge