server:
  port: 8888

spring:
  application:
    name: AuctionMarket

  sql:
    init:
      mode: always
      encoding: UTF-8

  data:
    redis:
      host: redis # ??? ?? ? 'redis' (???? ??)
      port: 6379

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: none #none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # MySQL 8.0 ??? ?? Dialect ?? ??
        dialect: org.hibernate.dialect.MySQL8Dialect

# JWT
jwt:
  # ?? ???? ? ??
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000